[models]

[models.gpt3]
name = "gpt-3.5-turbo"
description = "GPT-3.5 Turbo Model with 4096 tokens context window"

[models.gpt3.config]
temperature = 0.3
max_tokens = 150
n = 1
stop = []
stream = true

[models.gpt3_16]
name = "gpt-3.5-turbo-16k"
description = "GPT-3.5 Turbo Model with 16384 tokens context window"

[models.gpt3_16.config]
temperature = 0.3
max_tokens = 150
n = 1
stop = []
stream = true