
version: '3.3'

services:
  app-service:
    build: .
    stdin_open: true
    tty: true
    depends_on:
      - redis
    environment:
      - REDIS_PORT=6379
    volumes:
      - .:/app

  redis:
    image: "redis:alpine"